export type AwayTeam = {
     club_id?: number;
     team_id?: number,
     awayTeam_name:string,
     awayTeam_description:string,
     awayTeam_image:string,
     awayTeam_player1:string,
     awayTeam_player2:string,
     awayTeam_player3:string,
     awayTeam_player4:string,
     awayTeam_player5:string,
     awayTeam_player6:string,
     awayTeam_player7:string,
     awayTeam_player8:string,
     awayTeam_player9:string,
     awayTeam_player10:string,
     awayTeam_player11:string,
     awayTeam_player12:string,
     awayTeam_player13:string,
     awayTeam_player14:string,
     awayTeam_player15:string,
     awayTeam_player16:string,
     awayTeam_player17:string,
     awayTeam_player18:string,
     awayTeam_player19:string,
     awayTeam_player20:string,
     awayTeam_player21:string,
     awayTeam_player22:string,
   }
   